batch_size: 1
ckpt_freq: 100
data:
  data: ''
  eval_instruct_data: /share/pi/nigam/users/aunell/mistral-finetune/data/ultrachat_chunk_eval.jsonl
  instruct_data: /share/pi/nigam/users/aunell/mistral-finetune/data/ultrachat_chunk_train.jsonl
eval_freq: 100
log_freq: 1
lora:
  rank: 64
max_steps: 100
model_id_or_path: /share/pi/nigam/users/aunell/mistral-finetune/mistral_models
no_eval: false
num_microbatches: 8
optim:
  lr: 0.0001
  pct_start: 0.05
  weight_decay: 0.1
run_dir: /share/pi/nigam/users/aunell/mistral-finetune/test_ultra
save_adapters: true
seed: 0
seq_len: 2048
